sonar.projectKey=ananya-288_office-resource-booking-cdos
sonar.organization=ananya-288
sonar.python.version=3.9
sonar.python.coverage.reportPaths=coverage.xml
sonar.sources=bookings,office_resource_booking
sonar.exclusions=staticfiles/**,**/migrations/**
sonar.coverage.exclusions=**/tests/**,manage.py,office_resource_booking/wsgi.py,office_resource_booking/asgi.py,office_resource_booking/settings.py,office_resource_booking/urls.py